/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_mmapallocator_include_private_h__
#define _mulle_mmapallocator_include_private_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-mmap`
// (Use B9E896FB-FE26-42ED-9F81-88681FD3BD2F instead of mulle-mmap, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-mmap no-header`
//    rename              : `mulle-sde dependency|library set mulle-mmap include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-mmap <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-mmap [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-mmap [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-mmap [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-mmap no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-mmap/mulle-mmap.h>   // mulle-mmap

#endif
